config/routes.rb
Tarefas::Application.routes.draw do
  resources :tarefas

end

app/models/tarefa.rb
class Tarefa < ActiveRecord::Base
  attr_accessible :descricao, :titulo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  # GET /tarefas
  # GET /tarefas.json
  def index
    @tarefas = Tarefa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tarefas }
    end
  end

  # GET /tarefas/1
  # GET /tarefas/1.json
  def show
    @tarefa = Tarefa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tarefa }
    end
  end

  # GET /tarefas/new
  # GET /tarefas/new.json
  def new
    @tarefa = Tarefa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tarefa }
    end
  end

  # GET /tarefas/1/edit
  def edit
    @tarefa = Tarefa.find(params[:id])
  end

  # POST /tarefas
  # POST /tarefas.json
  def create
    @tarefa = Tarefa.new(params[:tarefa])

    respond_to do |format|
      if @tarefa.save
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully created.' }
        format.json { render json: @tarefa, status: :created, location: @tarefa }
      else
        format.html { render action: "new" }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tarefas/1
  # PUT /tarefas/1.json
  def update
    @tarefa = Tarefa.find(params[:id])

    respond_to do |format|
      if @tarefa.update_attributes(params[:tarefa])
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarefas/1
  # DELETE /tarefas/1.json
  def destroy
    @tarefa = Tarefa.find(params[:id])
    @tarefa.destroy

    respond_to do |format|
      format.html { redirect_to tarefas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tarefas</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tarefas/_form.html.erb
<%= form_for(@tarefa) do |f| %>
  <% if @tarefa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tarefa.errors.count, "error") %> prohibited this tarefa from being saved:</h2>

      <ul>
      <% @tarefa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tarefas/edit.html.erb
<h1>Editing tarefa</h1>

<%= render 'form' %>

<%= link_to 'Show', @tarefa %> |
<%= link_to 'Back', tarefas_path %>

app/views/tarefas/index.html.erb
<h1>Listing tarefas</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Descricao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tarefas.each do |tarefa| %>
  <tr>
    <td><%= tarefa.titulo %></td>
    <td><%= tarefa.descricao %></td>
    <td><%= link_to 'Show', tarefa %></td>
    <td><%= link_to 'Edit', edit_tarefa_path(tarefa) %></td>
    <td><%= link_to 'Destroy', tarefa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tarefa', new_tarefa_path %>

app/views/tarefas/new.html.erb
<h1>New tarefa</h1>

<%= render 'form' %>

<%= link_to 'Back', tarefas_path %>

app/views/tarefas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @tarefa.titulo %>
</p>

<p>
  <b>Descricao:</b>
  <%= @tarefa.descricao %>
</p>


<%= link_to 'Edit', edit_tarefa_path(@tarefa) %> |
<%= link_to 'Back', tarefas_path %>